# Generated by Django 4.1.5 on 2023-02-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_board_member_alter_user_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='board_member',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
    ]
