# Generated by Django 4.1.5 on 2023-02-12 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ministry_ministryrole_org_alter_user_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usa_State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
            ],
            options={
                'verbose_name_plural': 'Usa_States',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('selected_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usa_state', verbose_name='Usa_States')),
            ],
        ),
    ]
