# Generated by Django 4.1.5 on 2023-02-12 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usa_state_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterField(
            model_name='org',
            name='org_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city', verbose_name='Cities'),
        ),
        migrations.AlterField(
            model_name='org',
            name='org_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usa_state', verbose_name='Usa_States'),
        ),
    ]
