# Generated by Django 4.1.5 on 2023-02-12 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_city_options_alter_org_org_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ministryrole',
            name='ministry_department',
        ),
    ]
