# Generated by Django 4.1.5 on 2023-02-12 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_ministryrole_ministry_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ministryteammember',
            options={'verbose_name_plural': 'MinistryTeamMembers'},
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(blank=True, choices=[('FEMALE', 'Female'), ('MALE', 'Male')], max_length=10, null=True)),
                ('Marital Status', models.CharField(blank=True, choices=[('MARRIED', 'Married'), ('SINGLE', 'Single'), ('DIVORCED', 'Divorces'), ('WIDOWED', 'Widowed')], max_length=10, null=True)),
                ('Tier', models.CharField(blank=True, choices=[('ONE', '1'), ('TWO', '2'), ('THREE', '3')], max_length=10, null=True)),
                ('image_file', models.ImageField(default='default.jpg', upload_to=None)),
                ('street_number', models.IntegerField()),
                ('street_name', models.CharField(max_length=50)),
                ('street_suffix', models.CharField(max_length=50)),
                ('postal_code', models.IntegerField()),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('board_member', models.BooleanField(default=False)),
                ('assigned_elder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ministryteammember', verbose_name='MinistryTeamMembers')),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Users')),
                ('usr_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city', verbose_name='Cities')),
                ('usr_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usa_state', verbose_name='Usa_States')),
            ],
            options={
                'verbose_name_plural': 'UserDetails',
            },
        ),
    ]
