# Generated by Django 4.1.5 on 2023-02-12 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_ministryteammember_options_userdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='street_suffix',
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='assigned_elder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ministryteammember', verbose_name='MinistryTeamMembers'),
        ),
    ]
